### ISSUE TITLE
Repost request

### ISSUE THREAD

**Issue by LittleHed** [TheViperShow/SafeChat#4]
Hello, I am an Minecraft player from China,I think your plugin is very useful and helpful to my server. I would like to introduce it to the Chinese Minecraft forum.The link is www.mcbbs.net.

**Comment by TheViperShow** [comment]
You sure can, if you need any further customization for the plugin's text (in order for the chinese community to translate), I can provide it in future updates.

**Comment by LittleHed** [comment]
Thanks!I can translate it to chinese
